// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0vOuenPUuKz2Qso3XX8LFEmDmmDnqCs',
    appId: '1:269218573130:web:f4a849d9a3e7885202efb3',
    messagingSenderId: '269218573130',
    projectId: 'app-controle-financeiro-9a42d',
    authDomain: 'app-controle-financeiro-9a42d.firebaseapp.com',
    storageBucket: 'app-controle-financeiro-9a42d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mGXXb4t7yqSUf2mZfB6pYaUEK2xwG-A',
    appId: '1:269218573130:android:288cd26ff2281f6602efb3',
    messagingSenderId: '269218573130',
    projectId: 'app-controle-financeiro-9a42d',
    storageBucket: 'app-controle-financeiro-9a42d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIYuzDLbdmPu4FQEr0JPoVkOAcyYbuRfE',
    appId: '1:269218573130:ios:894b960da5215ba602efb3',
    messagingSenderId: '269218573130',
    projectId: 'app-controle-financeiro-9a42d',
    storageBucket: 'app-controle-financeiro-9a42d.appspot.com',
    iosBundleId: 'com.example.appControleFinaceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIYuzDLbdmPu4FQEr0JPoVkOAcyYbuRfE',
    appId: '1:269218573130:ios:894b960da5215ba602efb3',
    messagingSenderId: '269218573130',
    projectId: 'app-controle-financeiro-9a42d',
    storageBucket: 'app-controle-financeiro-9a42d.appspot.com',
    iosBundleId: 'com.example.appControleFinaceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw0vOuenPUuKz2Qso3XX8LFEmDmmDnqCs',
    appId: '1:269218573130:web:42ae665b6fd858c702efb3',
    messagingSenderId: '269218573130',
    projectId: 'app-controle-financeiro-9a42d',
    authDomain: 'app-controle-financeiro-9a42d.firebaseapp.com',
    storageBucket: 'app-controle-financeiro-9a42d.appspot.com',
  );
}
